// <auto-generated />
using FuscaFilmes.Repo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuscaFilmes.Repo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260208182952_InitialCraation")]
    partial class InitialCraation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diretores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ridley Scott"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Peter Jackson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Denis Villeneuve"
                        },
                        new
                        {
                            Id = 9,
                            Name = "George Lucas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Francis Ford Coppola"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiretorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretorId");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2010,
                            DiretorId = 1,
                            Titulo = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2014,
                            DiretorId = 1,
                            Titulo = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2008,
                            DiretorId = 1,
                            Titulo = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2017,
                            DiretorId = 1,
                            Titulo = "Dunkirk"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 1993,
                            DiretorId = 2,
                            Titulo = "Jurassic Park"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 1982,
                            DiretorId = 2,
                            Titulo = "E.T. - O Extraterrestre"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 1981,
                            DiretorId = 2,
                            Titulo = "Indiana Jones e Os Caçadores da Arca Perdida"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 1998,
                            DiretorId = 2,
                            Titulo = "O Resgate do Soldado Ryan"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 1994,
                            DiretorId = 3,
                            Titulo = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2003,
                            DiretorId = 3,
                            Titulo = "Kill Bill: Volume 1"
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2009,
                            DiretorId = 3,
                            Titulo = "Bastardos Inglórios"
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2012,
                            DiretorId = 3,
                            Titulo = "Django Livre"
                        },
                        new
                        {
                            Id = 13,
                            Ano = 1990,
                            DiretorId = 4,
                            Titulo = "Os Bons Companheiros"
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2013,
                            DiretorId = 4,
                            Titulo = "O Lobo de Wall Street"
                        },
                        new
                        {
                            Id = 15,
                            Ano = 1976,
                            DiretorId = 4,
                            Titulo = "Taxi Driver"
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2010,
                            DiretorId = 4,
                            Titulo = "Ilha do Medo"
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2009,
                            DiretorId = 5,
                            Titulo = "Avatar"
                        },
                        new
                        {
                            Id = 18,
                            Ano = 1997,
                            DiretorId = 5,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 19,
                            Ano = 1991,
                            DiretorId = 5,
                            Titulo = "O Exterminador do Futuro 2"
                        },
                        new
                        {
                            Id = 20,
                            Ano = 2000,
                            DiretorId = 6,
                            Titulo = "Gladiador"
                        },
                        new
                        {
                            Id = 21,
                            Ano = 1979,
                            DiretorId = 6,
                            Titulo = "Alien: O Oitavo Passageiro"
                        },
                        new
                        {
                            Id = 22,
                            Ano = 1982,
                            DiretorId = 6,
                            Titulo = "Blade Runner"
                        },
                        new
                        {
                            Id = 23,
                            Ano = 2001,
                            DiretorId = 7,
                            Titulo = "O Senhor dos Anéis: A Sociedade do Anel"
                        },
                        new
                        {
                            Id = 24,
                            Ano = 2002,
                            DiretorId = 7,
                            Titulo = "O Senhor dos Anéis: As Duas Torres"
                        },
                        new
                        {
                            Id = 25,
                            Ano = 2003,
                            DiretorId = 7,
                            Titulo = "O Senhor dos Anéis: O Retorno do Rei"
                        },
                        new
                        {
                            Id = 26,
                            Ano = 2016,
                            DiretorId = 8,
                            Titulo = "A Chegada"
                        },
                        new
                        {
                            Id = 27,
                            Ano = 2017,
                            DiretorId = 8,
                            Titulo = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 28,
                            Ano = 2021,
                            DiretorId = 8,
                            Titulo = "Duna"
                        },
                        new
                        {
                            Id = 29,
                            Ano = 1977,
                            DiretorId = 9,
                            Titulo = "Star Wars: Episódio IV – Uma Nova Esperança"
                        },
                        new
                        {
                            Id = 30,
                            Ano = 1999,
                            DiretorId = 9,
                            Titulo = "Star Wars: Episódio I – A Ameaça Fantasma"
                        },
                        new
                        {
                            Id = 31,
                            Ano = 1972,
                            DiretorId = 10,
                            Titulo = "O Poderoso Chefão"
                        },
                        new
                        {
                            Id = 32,
                            Ano = 1974,
                            DiretorId = 10,
                            Titulo = "O Poderoso Chefão II"
                        },
                        new
                        {
                            Id = 33,
                            Ano = 1979,
                            DiretorId = 10,
                            Titulo = "Apocalypse Now"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Filme", b =>
                {
                    b.HasOne("FuscaFilmes.Domain.Entities.Diretor", "Diretor")
                        .WithMany("Filmes")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretor");
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Diretor", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
