// <auto-generated />
using System;
using FuscaFilmes.Repo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuscaFilmes.Repo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260211224828_121_DiretorDetalhe")]
    partial class _121_DiretorDetalhe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diretores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "James Cameron"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ridley Scott"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Peter Jackson"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Denis Villeneuve"
                        },
                        new
                        {
                            Id = 9,
                            Name = "George Lucas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Francis Ford Coppola"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.DiretorDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiretorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiretorId")
                        .IsUnique();

                    b.ToTable("DiretorDetalhe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "Christopher Nolan é um cineasta britânico-americano conhecido por narrativas complexas e visuais inovadores.",
                            DataNascimento = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Biografia = "Steven Spielberg é um dos diretores mais influentes da história, responsável por clássicos do cinema moderno.",
                            DataNascimento = new DateTime(1946, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 2
                        },
                        new
                        {
                            Id = 3,
                            Biografia = "Quentin Tarantino é conhecido por seu estilo único, diálogos marcantes e narrativas não lineares.",
                            DataNascimento = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 3
                        },
                        new
                        {
                            Id = 4,
                            Biografia = "Martin Scorsese é um dos maiores diretores americanos, famoso por filmes sobre crime e personagens complexos.",
                            DataNascimento = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 4
                        },
                        new
                        {
                            Id = 5,
                            Biografia = "James Cameron é conhecido por grandes produções e inovações tecnológicas no cinema.",
                            DataNascimento = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 5
                        },
                        new
                        {
                            Id = 6,
                            Biografia = "Ridley Scott é um diretor britânico renomado por obras de ficção científica e épicos visuais.",
                            DataNascimento = new DateTime(1937, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 6
                        },
                        new
                        {
                            Id = 7,
                            Biografia = "Peter Jackson ganhou destaque mundial com a trilogia O Senhor dos Anéis.",
                            DataNascimento = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 7
                        },
                        new
                        {
                            Id = 8,
                            Biografia = "Denis Villeneuve é conhecido por sua estética visual marcante e narrativas profundas.",
                            DataNascimento = new DateTime(1967, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 8
                        },
                        new
                        {
                            Id = 9,
                            Biografia = "George Lucas é o criador da saga Star Wars e fundador da Lucasfilm.",
                            DataNascimento = new DateTime(1944, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 9
                        },
                        new
                        {
                            Id = 10,
                            Biografia = "Francis Ford Coppola é um dos grandes diretores do cinema americano, conhecido por O Poderoso Chefão.",
                            DataNascimento = new DateTime(1939, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DiretorId = 10
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.DiretorFilme", b =>
                {
                    b.Property<int>("DiretorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiretorId", "FilmeId");

                    b.HasIndex("FilmeId");

                    b.ToTable("DiretoresFilmes", (string)null);

                    b.HasData(
                        new
                        {
                            DiretorId = 1,
                            FilmeId = 1
                        },
                        new
                        {
                            DiretorId = 1,
                            FilmeId = 2
                        },
                        new
                        {
                            DiretorId = 1,
                            FilmeId = 3
                        },
                        new
                        {
                            DiretorId = 1,
                            FilmeId = 4
                        },
                        new
                        {
                            DiretorId = 2,
                            FilmeId = 5
                        },
                        new
                        {
                            DiretorId = 2,
                            FilmeId = 6
                        },
                        new
                        {
                            DiretorId = 2,
                            FilmeId = 7
                        },
                        new
                        {
                            DiretorId = 2,
                            FilmeId = 8
                        },
                        new
                        {
                            DiretorId = 3,
                            FilmeId = 9
                        },
                        new
                        {
                            DiretorId = 3,
                            FilmeId = 10
                        },
                        new
                        {
                            DiretorId = 3,
                            FilmeId = 11
                        },
                        new
                        {
                            DiretorId = 3,
                            FilmeId = 12
                        },
                        new
                        {
                            DiretorId = 4,
                            FilmeId = 13
                        },
                        new
                        {
                            DiretorId = 4,
                            FilmeId = 14
                        },
                        new
                        {
                            DiretorId = 4,
                            FilmeId = 15
                        },
                        new
                        {
                            DiretorId = 4,
                            FilmeId = 16
                        },
                        new
                        {
                            DiretorId = 5,
                            FilmeId = 17
                        },
                        new
                        {
                            DiretorId = 5,
                            FilmeId = 18
                        },
                        new
                        {
                            DiretorId = 5,
                            FilmeId = 19
                        },
                        new
                        {
                            DiretorId = 6,
                            FilmeId = 20
                        },
                        new
                        {
                            DiretorId = 6,
                            FilmeId = 21
                        },
                        new
                        {
                            DiretorId = 6,
                            FilmeId = 22
                        },
                        new
                        {
                            DiretorId = 7,
                            FilmeId = 23
                        },
                        new
                        {
                            DiretorId = 7,
                            FilmeId = 24
                        },
                        new
                        {
                            DiretorId = 7,
                            FilmeId = 25
                        },
                        new
                        {
                            DiretorId = 8,
                            FilmeId = 26
                        },
                        new
                        {
                            DiretorId = 8,
                            FilmeId = 27
                        },
                        new
                        {
                            DiretorId = 8,
                            FilmeId = 28
                        },
                        new
                        {
                            DiretorId = 9,
                            FilmeId = 29
                        },
                        new
                        {
                            DiretorId = 9,
                            FilmeId = 30
                        },
                        new
                        {
                            DiretorId = 10,
                            FilmeId = 31
                        },
                        new
                        {
                            DiretorId = 10,
                            FilmeId = 32
                        },
                        new
                        {
                            DiretorId = 10,
                            FilmeId = 33
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2010,
                            Titulo = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2014,
                            Titulo = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2008,
                            Titulo = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2017,
                            Titulo = "Dunkirk"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 1993,
                            Titulo = "Jurassic Park"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 1982,
                            Titulo = "E.T. - O Extraterrestre"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 1981,
                            Titulo = "Indiana Jones e Os Caçadores da Arca Perdida"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 1998,
                            Titulo = "O Resgate do Soldado Ryan"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 1994,
                            Titulo = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2003,
                            Titulo = "Kill Bill: Volume 1"
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2009,
                            Titulo = "Bastardos Inglórios"
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2012,
                            Titulo = "Django Livre"
                        },
                        new
                        {
                            Id = 13,
                            Ano = 1990,
                            Titulo = "Os Bons Companheiros"
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2013,
                            Titulo = "O Lobo de Wall Street"
                        },
                        new
                        {
                            Id = 15,
                            Ano = 1976,
                            Titulo = "Taxi Driver"
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2010,
                            Titulo = "Ilha do Medo"
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2009,
                            Titulo = "Avatar"
                        },
                        new
                        {
                            Id = 18,
                            Ano = 1997,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 19,
                            Ano = 1991,
                            Titulo = "O Exterminador do Futuro 2"
                        },
                        new
                        {
                            Id = 20,
                            Ano = 2000,
                            Titulo = "Gladiador"
                        },
                        new
                        {
                            Id = 21,
                            Ano = 1979,
                            Titulo = "Alien: O Oitavo Passageiro"
                        },
                        new
                        {
                            Id = 22,
                            Ano = 1982,
                            Titulo = "Blade Runner"
                        },
                        new
                        {
                            Id = 23,
                            Ano = 2001,
                            Titulo = "O Senhor dos Anéis: A Sociedade do Anel"
                        },
                        new
                        {
                            Id = 24,
                            Ano = 2002,
                            Titulo = "O Senhor dos Anéis: As Duas Torres"
                        },
                        new
                        {
                            Id = 25,
                            Ano = 2003,
                            Titulo = "O Senhor dos Anéis: O Retorno do Rei"
                        },
                        new
                        {
                            Id = 26,
                            Ano = 2016,
                            Titulo = "A Chegada"
                        },
                        new
                        {
                            Id = 27,
                            Ano = 2017,
                            Titulo = "Blade Runner 2049"
                        },
                        new
                        {
                            Id = 28,
                            Ano = 2021,
                            Titulo = "Duna"
                        },
                        new
                        {
                            Id = 29,
                            Ano = 1977,
                            Titulo = "Star Wars: Episódio IV – Uma Nova Esperança"
                        },
                        new
                        {
                            Id = 30,
                            Ano = 1999,
                            Titulo = "Star Wars: Episódio I – A Ameaça Fantasma"
                        },
                        new
                        {
                            Id = 31,
                            Ano = 1972,
                            Titulo = "O Poderoso Chefão"
                        },
                        new
                        {
                            Id = 32,
                            Ano = 1974,
                            Titulo = "O Poderoso Chefão II"
                        },
                        new
                        {
                            Id = 33,
                            Ano = 1979,
                            Titulo = "Apocalypse Now"
                        });
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.DiretorDetalhe", b =>
                {
                    b.HasOne("FuscaFilmes.Domain.Entities.Diretor", "Diretor")
                        .WithOne("DiretorDetalhe")
                        .HasForeignKey("FuscaFilmes.Domain.Entities.DiretorDetalhe", "DiretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretor");
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.DiretorFilme", b =>
                {
                    b.HasOne("FuscaFilmes.Domain.Entities.Diretor", "Diretor")
                        .WithMany("DiretoresFilmes")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuscaFilmes.Domain.Entities.Filme", "Filme")
                        .WithMany("DiretoresFilmes")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretor");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Diretor", b =>
                {
                    b.Navigation("DiretorDetalhe");

                    b.Navigation("DiretoresFilmes");
                });

            modelBuilder.Entity("FuscaFilmes.Domain.Entities.Filme", b =>
                {
                    b.Navigation("DiretoresFilmes");
                });
#pragma warning restore 612, 618
        }
    }
}
